version: '3.3'

services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    volumes:
      - db_data_mysql:/mssql/data
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'manager'
    ports:
      - '3306:3306'
    expose:
        - '3306'

volumes:
  db_data_mysql: